{% set version = "1.13.0" %}


package:
  name: gtest
  version: {{ version }}

source:
  url: https://github.com/google/googletest/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ad7fdba11ea011c1d925b3289cf4af2c66a352e18d4c7264392fead75e919363

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}        # [ ppc_arch != "p10"]
    - python {{ python }}
    - cmake {{ cmake }}
    - ninja {{ ninja }}

outputs:
  - name: gtest
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}     # [ ppc_arch != "p10"]
        - python {{ python }}
        - cmake {{ cmake }}
        - ninja {{ ninja }}
      run_constrained:
        - gmock {{ version }}
    files:
      -  lib/libgtest*                                          # [linux]
      -  include/gtest                                          # [linux]
      -  lib/pkgconfig/gtest*.pc                                # [linux]
      -  lib/cmake/GTest                                        # [linux]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libgtest.a                    # [linux]
        - test ! -f ${PREFIX}/lib/libgtest_main.a               # [linux]
        - test -f ${PREFIX}/lib/libgtest${SHLIB_EXT}            # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gtest.pc              # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gtest_main.pc         # [linux]
        - test -d ${PREFIX}/include/gtest                       # [linux]

  - name: gmock
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}     # [ ppc_arch != "p10"]
        - python {{ python }}
        - cmake {{ cmake }}
        - ninja {{ ninja }}
      host:
        - {{ pin_subpackage('gtest', exact=True) }}
      run:
        - {{ pin_subpackage('gtest', exact=True) }}
    files:
      -  include/gmock                                          # [linux]
      -  lib/libgmock*                                          # [linux]
      -  lib/pkgconfig/gmock*.pc                                # [linux]
      -  lib/cmake/GTest                                        # [linux]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libgmock.a                    # [linux]
        - test ! -f ${PREFIX}/lib/libgmock_main.a               # [linux]
        - test -f ${PREFIX}/lib/libgmock${SHLIB_EXT}            # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gmock.pc              # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gmock_main.pc         # [linux]
        - test -d ${PREFIX}/include/gmock                       # [linux]

about:
  home: https://github.com/google/googletest
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Google's C++ test framework

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
