{% set version = "1.10.0" %}


package:
  name: gtest
  version: {{ version }}

source:
  url: https://github.com/google/googletest/archive/release-{{ version }}.tar.gz
  sha256: 9dc9157a9a1551ec7a7e43daea9a694a0bb5fb8bec81235d8a1e6ef64c716dcb

build:
  number: 3 

requirements:
  build:
    - {{ compiler('cxx') }}        # [ ppc_arch != "p10"]
    - python {{ python }}
    - cmake {{ cmake }}
    - ninja {{ ninja }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                                   # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}                             # [x86_64 and c_compiler_version == "7.2.*"]
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                                   # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}                             # [x86_64 and c_compiler_version == "7.2.*"]

outputs:
  - name: gtest
    version: {{ version }}
    requirements:
      host:
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}                               # [x86_64 and c_compiler_version == "7.2.*"]
        - libstdcxx-ng  {{ libstdcxx }}                         # [x86_64 and c_compiler_version == "7.2.*"]
      build:
        - {{ compiler('cxx') }}     # [ ppc_arch != "p10"]
        - python {{ python }}
        - cmake {{ cmake }}
        - ninja {{ ninja }}
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}                               # [x86_64 and c_compiler_version == "7.2.*"]
        - libstdcxx-ng  {{ libstdcxx }}                         # [x86_64 and c_compiler_version == "7.2.*"]
      run_constrained:
        - gmock {{ version }}
    files:
      -  lib/libgtest*                                          # [linux]
      -  include/gtest                                          # [linux]
      -  lib/pkgconfig/gtest*.pc                                # [linux]
      -  lib/cmake/GTest                                        # [linux]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libgtest.a                    # [linux]
        - test ! -f ${PREFIX}/lib/libgtest_main.a               # [linux]
        - test -f ${PREFIX}/lib/libgtest${SHLIB_EXT}            # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gtest.pc              # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gtest_main.pc         # [linux]
        - test -d ${PREFIX}/include/gtest                       # [linux]

  - name: gmock
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}     # [ ppc_arch != "p10"]
        - python {{ python }}
        - cmake {{ cmake }}
        - ninja {{ ninja }}
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}                               # [x86_64 and c_compiler_version == "7.2.*"]
        - libstdcxx-ng  {{ libstdcxx }}                         # [x86_64 and c_compiler_version == "7.2.*"]
      host:
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}                               # [x86_64 and c_compiler_version == "7.2.*"]
        - libstdcxx-ng  {{ libstdcxx }}                         # [x86_64 and c_compiler_version == "7.2.*"]
        - {{ pin_subpackage('gtest', exact=True) }}
      run:
        - {{ pin_subpackage('gtest', exact=True) }}
    files:
      -  include/gmock                                          # [linux]
      -  lib/libgmock*                                          # [linux]
      -  lib/pkgconfig/gmock*.pc                                # [linux]
      -  lib/cmake/GTest                                        # [linux]
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libgmock.a                    # [linux]
        - test ! -f ${PREFIX}/lib/libgmock_main.a               # [linux]
        - test -f ${PREFIX}/lib/libgmock${SHLIB_EXT}            # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gmock.pc              # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/gmock_main.pc         # [linux]
        - test -d ${PREFIX}/include/gmock                       # [linux]

about:
  home: https://github.com/google/googletest
  license: BSD-3-Clause
  license_family: BSD
  license_file: googletest/LICENSE
  summary: Google's C++ test framework

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
